# UCA with I3D features  
# ====================================================================
# UCA Dataset Configuration for PDVC with I3D Features
# For Table 8 (Dense Video Captioning with Ground-Truth Proposals)
# Ground-Truth Proposals Mode
# ====================================================================

# Dataset paths
train_caption_file: data/uca/captiondata/train.json
val_caption_file: data/uca/captiondata/val.json
test_caption_file: data/uca/captiondata/test.json

# I3D visual features
visual_feature_folder: data/uca/features/i3d
video_feature_size: 1024

# Vocabulary
vocab_file: data/uca/captiondata/vocabulary.json
word_count_threshold: 5
max_caption_len: 30

# Model Architecture
model:
  type: PDVC
  num_queries: 100
  hidden_dim: 256
  position_embedding: sine
  nheads: 8
  num_encoder_layers: 6
  dim_feedforward: 1024
  num_decoder_layers: 6
  dropout: 0.1
  input_dim: 1024
  max_eseq_length: 10
  num_events: 100
  caption_decoder_type: standard
  set_cost_class: 4
  set_cost_bbox: 5
  set_cost_giou: 2
  bbox_loss_coef: 5
  giou_loss_coef: 2
  eos_coef: 0.4
  aux_loss: true

# Training Settings (RTX 4070 OPTIMIZED)
train:
  batch_size: 1
  num_workers: 4
  prefetch_factor: 2
  pin_memory: true
  epochs: 200
  learning_rate: 0.0001
  lr_drop: 100
  weight_decay: 0.0001
  clip_max_norm: 0.1
  optimizer: AdamW
  lr_scheduler: step
  save_checkpoint_every: 10
  save_model: true
  eval_epoch: 10
  eval_init: false
  gradient_checkpointing: false
  empty_cache_every: 50

# Evaluation Settings
eval:
  batch_size: 1
  num_workers: 4
  eval_proposal_type: queries
  sample_topk: 1
  max_caption_len: 30

# Mixed Precision Training
amp:
  enabled: true
  opt_level: O1
  loss_scale: dynamic

# Other Settings
data_augmentation:
  temporal_augmentation: false
  random_crop: false

logging:
  log_dir: logs/uca_i3d_pdvc
  tensorboard: true
  print_freq: 50
  save_every: 100
  
visualization:
  save_video: false
  vis_dir: visualization/uca_i3d_pdvc

device: cuda
gpu_id: 0
distributed: false
seed: 42
deterministic: false

dataset_name: UCA
dataset_type: dense_video_captioning
feature_type: i3d
feature_dim: 1024
feature_framerate: 1.5
max_video_len: 300
max_num_events: 10

resume: null
pretrained_model: null
eval_only: false